name: Manual workflow
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Get Containerlab Version
      run: containerlab version
    - name: Deploy Lab
      run: containerlab deploy -t topology.yml
    - name: Sleep for 30 seconds
      run: sleep 30s
    - name: Print first boot configuration
      run: cat clab-xrdtest/*/first-boot.cfg
    - name: Destroy lab
      run: containerlab destroy -t topology.yml --cleanup
