name: Manual workflow
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Get Containerlab Version
      run: containerlab version
    - name: Run topology file
      run: |
        containerlab deploy -t topology.yml
